name: Publish NuGet Package

on:
  push:
    branches: [ master ]

env:
  NUGET_SOURCE: https://nuget.pkg.github.com/caiofabiogomes/index.json
  PACKAGE_OUTPUT_DIR: ./nupkg

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Create and push new Git tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag "v${{ env.PACKAGE_VERSION }}"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/caiofabiogomes/Tech

    
