name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: .NET Config
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    
      - name: Remove Existing NuGet Source
        run: dotnet nuget remove source github || true

      - name: Add GitHub NuGet Source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Create Package Nuget
        run: dotnet pack --configuration Release --no-build --output nupkgs

      - name: Publish in GitHub Packages
        run: dotnet nuget push nupkgs/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      - name: Clean Packages Locally
        run: rm -rf nupkgs/
